### ISSUE TITLE
Add support for multiple args with same flag

### ISSUE THREAD

**Issue by mitinarseny** [milewski/bin-exec-loader#42]
Hello! Firstly, thank you for developing this loader.

Could you please add support for multiple args with same flag? eg:
```bash
some_command --flag 1 --flag 2 --flag 3 --other-flag "value"
```
At the moment it is not possible to do it, as JS object remembers only last occurrence of given flag

**Comment by mitinarseny** [comment]
it should also preserve the order of arguments

**Comment by milewski** [comment]
If I recall correctly this could be done by doing something like `{ flag$0: 1, flag$1: 2 }` etc...
