### ISSUE TITLE
Build fails with this loader

### ISSUE THREAD

**Issue by Scindix** [milewski/bin-exec-loader#43]
This loader seems great. Exactly what I need. However it fails with the following error:
```
ERROR in ./src/test.json.gen
Module build failed (from ./node_modules/bin-exec-loader/source/loader.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Object.writeFileSync (node:fs:1505:5)
    at Function.module.exports.sync (./node_modules/temp-write/index.js:42:5)
    at Object.execBuffer (./node_modules/bin-exec-loader/source/exec.js:21:66)
    at Object.default_1 (./node_modules/bin-exec-loader/source/loader.js:54:12)
 @ ./src/index.js 2:0-35 3:12-16
```
I dug through the code and it seems that [this line](https://github.com/milewski/bin-exec-loader/blob/e7ec7ec163b2958795333041adaee8976485d760/source/exec.ts#L23) is the issue,
According to [the temp-write docs](https://developer.aliyun.com/mirror/npm/package/temp-write) the first argument of `tempWrite.sync` can only be a `string`, `Buffer` or `stream.Readable`.

So I changed the aforementioned line ([exec.ts:23](https://github.com/milewski/bin-exec-loader/blob/e7ec7ec163b2958795333041adaee8976485d760/source/exec.ts#L23)) from this
```js
output: multiple ? ensureDir(file) : tempWrite.sync(null, file)
```
to this
```js
output: multiple ? ensureDir(file) : tempWrite.sync("", file)
```
And it seems to work now.
Would it be possible to fix this issue? Otherwise I would have to fork and maintain my own patched version.

**Comment by aschempp** [comment]
I'm having the same issue, changing the mentioned line fixed the issue for me.

**Comment by aschempp** [comment]
any updates on this issue?

**Comment by milewski** [comment]
If either of you could send a PR, would be happy to merge, although I think webpack has been long gone by now ...

**Comment by aschempp** [comment]
well it is not _gone_ for me 😂  here's the PR: https://github.com/milewski/bin-exec-loader/pull/44
